package com.clinic.model.enums;

public enum Specialization {
    GENERAL_PRACTICE, CARDIOLOGY, DERMATOLOGY, PEDIATRICS,
    ORTHOPEDICS, NEUROLOGY, GYNECOLOGY, OPHTHALMOLOGY, GENERAL_PHYSICIAN, DENTISTRY
}
